### ISSUE TITLE
Game lock when using Rage strike

### ISSUE THREAD

**Issue by DiesIrea1** [X2CommunityCore/X2WOTCCommunityHighlander#1031]
Game locks when trying to use the rage armour. I use the BETA highlander and the DLC2 plugin. It locks after actually using the attack. You can still see the yellow squares where you can choose which to attack from. To get out of it I have to control alt delete sign out and then cancel it or resign in. I have attached the aml mod list and save file. It is currently equipped on an akimbo class
[AML.txt](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/6758673/AML.txt)
[save_AUTOSAVE- Campaign 40, Mission 66, Turn 7.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/6758689/save_AUTOSAVE-.Campaign.40.Mission.66.Turn.7.zip)

Didn't happen before the CHL BETA update

**Comment by Iridar** [comment]
I was able to replicate this with only Highlander and DLC2 Highlander active, so this indeed seems to be the fault of the current build somehow.

**Comment by Iridar** [comment]
Nothing useful in the log when this happens.

**Comment by Iridar** [comment]
The bug appears to trigger only sometimes, haven't narrowed down the exact circumstances.

**Comment by Iridar** [comment]
Issue appears to happen with standard Sword Slice as well.

**Comment by Iridar** [comment]
As a recap of an extended debugging session, it appears the hang is caused by triggering any event in the codepath that follows activating a moving melee ability, where the ability activation is confirmed by a left click or hitting spacebar. 

Right clicking on the tile to use the melee doesn't cause the hang. 

The hang seems to occur whenever any event is triggered in `UITacticalHUD_AbilityContainer::ConfirmAbility()` on the line directly preceding the `XComPresentationLayer(Owner.Owner).PopTargetingStates()` or anywhere after that point.

The current speculation is that:

> "we are triggering an event on the UI thread, while the manager expects to be on the latent submission thread, corrupting something internally" (c) Xymanek. 

Interestingly, the hang does not seem to happen when I trigger events in the same places in the code with the rest of the Highlander rolled back to 1.21.1

Pending further investigation.

The delegate system implemented in #889 might necessary as a replacement to the events added in #400 and #749. For now these events have been disabled in 1.22.1.

**Comment by Iridar** [comment]
Further investigation has shown that the problem was caused by an event trigger in `XCGS_Unit::HasHeightAdvantageOver()` added by #852, which caused a hang whenever a unit used a moving melee ability and an event was triggered "on the line directly preceding the XComPresentationLayer(Owner.Owner).PopTargetingStates() or anywhere after that point."

According to tests, any event in `X2AbilityToHitCalc_StandardAim::GetHitChance()` or in any function called by it will have the same effect as the event in `XCGS_Unit::HasHeightAdvantageOver()`. We can only speculate why this happens, but this is now the second time an event in To Hit Chance calculation logic has caused issues.

So from this point on, there is a ban on any event triggers in To Hit Chance calculation code. #852 was reverted and reimplemented using the delegate system.
