### ISSUE TITLE
Projectile Particle System Components are cleaned up too soon

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1061]
While fixing #720 by #1013, we created another problem: all spawned particle effects are cleaned up the moment projectile hits.

For comparison, here are the videos of firing the heavy weapon rocket launcher in CHL 1.21 and CHL 1.22:

* 1.21: https://youtu.be/gyUuhWBpsvA
* 1.22: https://youtu.be/Hm4xz083wjI

Notice how in the second video the rocket's smoke trail abruptly disappears the moment the rocket hits. 

This is only a visual bug, but a pretty egregious one. By fixing the "memory leak" we essentially broke *all* projectile trails.

**Comment by Xymanek** [comment]
Great catch! IMO this deserves 1.22.5, rather than waiting for all the features in 1.23.0.

As for the cause - I suspect we overlooked a small detail in #1013. The problem that we were fixing was `ParticleSystemComponent::OnSystemFinished` being overridden by `X2UnifiedProjectile::OnParticleSystemFinished`, but the calls to `MyEmitterPool.OnParticleSystemFinished` were added in 4 places, not in just the overridden callback handler.

IMO in the other 3 places, instead of directly calling `MyEmitterPool.OnParticleSystemFinished`, we should first check if the system has finished. If yes, inform the pool, otherwise **set the delegate back to the pool**'s one

**Comment by Iridar** [comment]
> Great catch! IMO this deserves 1.22.5, rather than waiting for all the features in 1.23.0.

Sure, I don't mind. Maybe include #1008 and #1030 as well?

> As for the cause - I suspect we overlooked a small detail in #1013. The problem that we were fixing was `ParticleSystemComponent::OnSystemFinished` being overridden by `X2UnifiedProjectile::OnParticleSystemFinished`, but the calls to `MyEmitterPool.OnParticleSystemFinished` were added in 4 places, not in just the overridden callback handler.
> 
> IMO in the other 3 places, instead of directly calling `MyEmitterPool.OnParticleSystemFinished`, we should first check if the system has finished. If yes, inform the pool, otherwise **set the delegate back to the pool**'s one

Sorry, I'm a bit lost with this. From what I understand, you're saying that we should leave **[this](https://github.com/Iridar/X2WOTCCommunityHighlander/blob/fa640930900688ec420f7f83b2eb62e0f0c9ba4c/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2UnifiedProjectile.uc#L1100)** as it is, but in other places where #1013 added something, we need to add a check if the particle system has completed? But where, exactly? Right before `WorldInfo.MyEmitterPool.OnParticleSystemFinished()`, or elsewhere? I'm happy to test the code, if you're willing to implement something. It's probably gonna be faster than for you to explain to me what exactly needs to be done.

**Comment by Xymanek** [comment]
Situation appears to be less clear than I thought initially - discussion continued in discord
