### ISSUE TITLE
Add an 'OnCrewMemberAdded' event

### ISSUE THREAD

**Issue by 0xStarcat** [X2CommunityCore/X2WOTCCommunityHighlander#1068]
In `XComGameState_HeadquartersXCom.OnCrewMemberAdded()` I think it'd be really useful to add an event which always fires. 

This method is linked to `XComGameState_HeadquartersXCom.AddToCrew()` which gets called from virtually any context which gives you a unit (as far as I can see): On recruiting a soldier, scientist, engineer, building a SPARK, on receiving a `PersonnelReward` so covert ops, avenger scanning, rescue missions, etc, even on creating tygen, shen, and bradford. 

I have a few use cases for it in my modding, and I'm sure other people would too. If you can access this event through a listener here, you could avoid a few class overrides or having to track down a lot of different events. I'm trying to create a persistent personnel history system to track mission and soldier events like how someone was recruited, what missions they went on, when they were captured / rescued, etc.

What do you think?

For clarity:
I'm asking for a different event than the existing `NewCrewNotification` event which is tied to showing a popup but is squelched when a unit is rescued from being captured. I'd like to be able to run some code when a unit is rescued from a capture here as well as in other situations from this event.

**Comment by Iridar** [comment]
Initially I added this to the latest milestone without looking much, cuz I thought it would be useful to have an event when a new crew member is added, but I didn't realize there already was an `NewCrewNotification` event for that, which I think covers most bases. Since nothing happened with this issue in 2 years, I'll go ahead and close it, feel free to reopen it if necessary.
