### ISSUE TITLE
Non-kevlar appearance for Character Pool soldiers is not retained

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2WOTCCommunityHighlander#1074]
Reproduction steps:

1. Debug strategy start.
2. Pick a soldier that doesn't exist in character pool yet.
3. Customize their appearance for several different armors, including Kevlar.
4. Save the soldier to character pool.
5. Exit, do more debug strategy starts until you get the soldier customize earlier.

Expected behavior at this point: soldier's appearance for different armors should be already customized. 
Actual behavior: soldier's appearance is customized only for kevlar. 

It seems when a character is created from the character pool, the game just copies their appearance, but not appearance store.

**Comment by Xymanek** [comment]
I suspect the issue lies here:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/e000ea357ba9ca3260ca14c43c1a13a13edc75ac/X2WOTCCommunityHighlander/Src/XComGame/Classes/CharacterPoolManager.uc#L24-L39

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/e000ea357ba9ca3260ca14c43c1a13a13edc75ac/X2WOTCCommunityHighlander/Src/XComGame/Classes/CharacterPoolManager.uc#L120-L167

To save space (presumably) FXS serializes only a couple of fields from `XComGameState_Unit` into the character pool - `AppearanceStore` not among them

**Comment by Iridar** [comment]
Yeah, I was just writing the same thing. This is very unfortunate, because it means units saved in character pool can never benefit from per-armor appearance, unless we do some hacking around, like creating multiple character pool entries for each soldier, one per different armor, which would probably create more issues than solve. 

Closing this issue as unsalvageable.
