### ISSUE TITLE
Randomly closes on second movie intro.

### ISSUE THREAD

**Issue by Kapparinoz** [X2CommunityCore/X2WOTCCommunityHighlander#1240]
Hello, not sure if ur still active with this project or not, but why not try.
I tried to start up with CLH and the game just closes when the 2nd intro "video/movie" start, its just randomly closes. 
Tried without CHL, and it worked fine. Is there anything i do wrong?

Attaching the log and photo right when it closes, and hope u can help me if u still active :)

[XCom-CL469133-2023.08.16-01.52.46_Logfile.log](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/12353969/XCom-CL469133-2023.08.16-01.52.46_Logfile.log)
![XCom-CL469133-2023 08 16-01 52 46_Screenshot](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/assets/142363881/5037c8a3-26a1-461d-8c15-b01da2d64085)

**Comment by BlackDog86** [comment]
This might be better suited to a discussion in the troubleshooting channel in the modding discord rather than raising a CHL issue for it. The CHL team is very much active but this is extremely likely to be a local problem - if CHL was crashing the game for everyone on the intro screen we'd certainly know about it, given the mod has over half a million subscribers ;)

**Comment by Iridar** [comment]
Based on your log, it seems you're using quite a few more mods than just the Highlander. While the game does crash for some people with just the Highlander active, and there are **[troubleshooting steps](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting)** that usually help in those cases, in your case it's more likely the issue is caused by another mod. 

Follow standard **[mod troubleshooting](https://www.reddit.com/r/xcom2mods/wiki/mod_troubleshooting)** steps, if you require further help, you can ask for it in the #troubleshooting channel of the [modmaking discord](https://discord.gg/ZytsZ93).
