### ISSUE TITLE
Compatibility with Musashi's "WotC Customize Soldier Size" Mod 

### ISSUE THREAD

**Issue by ryrytiedye** [X2CommunityCore/X2WOTCCommunityHighlander#264]
Hello,

The aforementioned mod is located [here](https://steamcommunity.com/sharedfiles/filedetails/?id=1147128235&searchtext=+X2WOTCCommunityHighlander).

Musashi assures that the X@WOTCCommunityHighlander is required for their mod to work. I have them both installed through the Alternative Mod Launcher.

The issue I am facing is that the soldiers' sizes can be modified through the Customization menu, but as soon as the menu is exited, the changes are reverted. 

I think the Highlander is failing to "retain" the changes imposed by this mod to take effect outside of the Customization menu.

Just thought I'd mention this :) not a high priority or anything!! Thanks for all that you do.

I'll try to find another solution in the meantime.

**Comment by robojumper** [comment]
Hello @ryrytiedye, thank you for your bug report. Sadly, I don't think this is an actionable issue for us because the Highlander itself doesn't save the changed unit size, it only enables other mods to change the unit size when they ask for it -- mods still have to save the sizes themselves.

Is the Highlander actually enabled in the game? You can verify this by checking the version string in the lower right corner on the main menu -- it should say something like `X2WOTCCommunityHighlander v1.11.1`.

**Comment by ryrytiedye** [comment]
@robojumper I appreciate the response! And I see!

That's odd--I have Windows Highlander downloaded onto my Windows10 computer and the Alternative Mod Launcher is showing that it's enabled, but I do not see the version string on the main menu like you mentioned. 

I'll play with things a bit to see if I can resolve this :)

**Comment by ryrytiedye** [comment]
@robojumper Success (for now)!

Using a fix provided on reddit ([here](https://www.reddit.com/r/Xcom/comments/7t9x3d/normal_to_have_these_messages_with_community/)) I was able to see the version string on the main menu.

Apparently, I had to use the files in the Highlander's CookedPCConsole folder to replace the ones in the corresponding CookedPCConsole folder in the Steam directory.

**Comment by robojumper** [comment]
Glad to hear. Generally, replacing files should not be necessary, but we should probably include that in a Troubleshooting section at some point.
