### ISSUE TITLE
Make TLP attitudes provide personality speeches

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#317]
XGUnit has a beautiful function that adds this to base game attitudes:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/8954b83b97d6296e26003dea22ea32da2af76c4f/X2WOTCCommunityHighlander/Src/XComGame/Classes/XGUnit.uc#L1441-L1562

Should be very simple to extend to TLP attitudes in a way that can easily be configured.

**Comment by Iridar** [comment]
#360 makes personality speech per attitude to be configurable, but does not add new personality speech for TLP attitudes. 

This mod does, though: https://steamcommunity.com/sharedfiles/filedetails/?id=1547952490

Attempting to contact the author for the permission to repurpose and merge it into CHI.

**Comment by Iridar** [comment]
I have obtained permission of the mod author to enroll her TLP personality config into Highlander. Her only condition was that this change remains backwards compatible with her mod, which it automatically should be, since her mod MCOs XGUnit, rendering any changes we do to `MaybeAddPersonalityToSpeech()` irrelevant.
