### ISSUE TITLE
List of almost every WotC-relevant Fix Mod

### ISSUE THREAD

**Issue by ghost** [X2CommunityCore/X2WOTCCommunityHighlander#32]
Thought this might be useful

(NEW LIST BELOW)

~~Also Ruler Nerf Nerf 1123973745 might be worth including since it touches on an unintended exploit. Fusion Ripjack Applies Stun 1128495039 is also worth considering since by default, the beam ripjack is a downgrade from the magnetic ripjack.~~

~~Ability Interaction Fixes and Damage Flyover Fix conflict with each other because they both fix different flyover texts.~~

**Comment by bountygiver** [comment]
btw things like loot mind control could use a better implementation if we are making it highlander as i am avoiding overwriting big classes.

**Comment by robojumper** [comment]
Hi Lady-Luck,

thanks for the List! We will take a look at the mods and decide which of them can be incorporated.

Generally, we try to not include any gameplay changes other than things that fix something that is definitely a bug (such as Lost World Fix), and several of these mods don't benefit from being in a Highlander such as Missing Packages Fix + Resource or the Evac Zone Fix.

**Comment by Lady-Luck** [comment]
I think you should incorporate every bugfix and common sense fix you can find, much like Unofficial Skyrim Patch and Unofficial Fallout 4 Patch, for instance. It'll help grow your contributors and bring more people to the mod, plus the end user's mod list is much smaller and has to do a lot less searching for all the fixes.

**Comment by abatewongc** [comment]
I'm not sure if this is the best place to be making bugfixes unless they are absolutely necessary (require overrides). From a purity of purpose standpoint, this project is primarily for expanding the capabilities of modders. The [Readme.md](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander#what-is-the-x2wotccommunityhighlander) says that clearly enough.

That said, an unofficial patch is certainly a good idea, if only because the tag 'Unofficial Patch' carries good branding. Making it a separate project dependent on the highlander would allow the highlander to benefit from that branding.

**Comment by MalucoMarinero** [comment]
The problem with that is the two mods would compete with each other. I'm of the thinking that community fixes should test the water as standalone mods, override or not, and then the Highlander should adopt bugfixes that require overrides, clearly work, and are essentially considered mandatory in terms of the vanilla experience. Separating is a non starter in my mind because of the highlander collision issue, otherwise I'd think it was a good idea.

**Comment by MalucoMarinero** [comment]
but that depends on the nature of 'Unofficial Patch' of course, rereading your post.

**Comment by Lady-Luck** [comment]
Problems arise when bugfixes conflict with content or gameplay mods, or bugfixes conflicting with other bugfixes (an example listed above where Ability Interaction Fixes conflicted with another bugfix because they both fix certain text flyovers).

That's why I think it's a good idea for them to be handled at the Highlander level.

**Comment by robojumper** [comment]
Damage Flyover Fix definitely fixes a base-game bug, so it could be included. (FYI, Ability Interaction Fixes includes all the functionality of Damage Flyover Fix).

However, your list of mods has many more mods, a lot of them can work without any conflicts and may not be for everyone because they make gameplay changes. This is why I disagree with including "every common sense fix".
If mods that we don't include directly make changes that cause conflicts, we can still work something out like adding additional hooks or functions to the Highlander that these mods can use.

**Comment by Lady-Luck** [comment]
It does? I don't see anything in Ability Interaction Fixes about Lightning Reflexes.

**Comment by Lady-Luck** [comment]
A new list, I've stripped out the more subjective common sense tweaks and focused on fixes:

AWC Squadsight Fix
Ability Interaction Fixes
Allies Unknown Evac Zone Fix
Ammo Pocket Fix
Brutal Fix
Chosen Dark Events Fix
Darkclaw Ammo Fix
Debug Items Fix
Defense Matrix Sabotage Fix
Exclude Same Class Skills
Faceoff Ammo Fix
Facility Clearing UI Indicator Fix
Insider Knowledge Fix
Loot Mind Control
Lost World Fix
Mec Micro Missile Launcher Color Fix
Missing Packages Fix + Resource
Missing Packages Fix - Parcels and Maps Edition
Revival Protocol Fixes
Supply Extraction Fix
Suppression Visualization Fix
Tracking Shot Defence

I'm not a modder so I don't know which ones are best to apply to Highlander, I just figure the list is useful.

**Comment by korgano** [comment]
From what I can tell, Exclude Same Class Skills is already in the highlander, just done through a check in the random class ability roll script to prevent duplicates of that class's abilities.

**Comment by Lady-Luck** [comment]
Good to know.

New additions:
Skulljack Feedback Fix
Sparks T-Pose Fix
Stop Suppressing The Lost AI Fix
Tower Detection Fix

Stop Suppressing The Lost AI Fix is a brand new fix for WOTC, the other 2 are old fixes that still work for WOTC and are still needed.

I once again endorse incorporating all possible bugfixes into this mod given the fact WOTC has made things complicated, with many old fixes still being needed while others are not.

**Comment by tunbridgep** [comment]
I would very much endorse adding the **Skyranger Lift Sound Fix** as it has been working extremely reliably since vanilla, and fixes one of the most annoying (although not game-breaking) bugs in the vanilla game.

Just to weigh in on the discussion, it could be argued that virtually every bugfix also counts as a gameplay change, as bugfixes will invariably modify existing gameplay. I guess it might be worthwhile creating some sort of "reasonableness test" for any given bugfix to stop infighting/disagreements about what constitutes a bugfix and what constitutes a gameplay mod.

A good example is Brutal Fix. I know Brutal Fix was fixed in a patch so it's no longer an issue, but it still makes a good analogy. Fixing it, even though it is clearly a bug, would inevitably change the gameplay quite a bit, because going from a permanent loss of will to a temporary loss of will can change the outcome of an entire campaign. There is a very noticeable change in gameplay, which someone may not want. On the other hand it is clearly a bug, with very obvious broken code.

I guess this might come across as a ramble, but I believe that if there isn't some sort of standard for what constitutes a significant enough gameplay change or not, then I think some mods which should really be included won't be (and possibly vice versa) because of differences of opinion on their severity/necessity and gameplay impact.

That said, I think having bugfixes as part of the highlander is quite important. Especially if Long War 2 is eventually going to be ported to WOTC, as base-game bugs may either be falsely reported as LW2 bugs, or fixes for base game bugs may be incompatible with LW2, meaning people will have to use special versions and then you have dependency hell. I know the Community Highlander is not Long War 2, but if the original highlander is anything to go by, since it was side-by-side with Long War 2, I assume this one will be as well, especially now that the WotC version of Long War 2 has been passed to the new team.

**Comment by Pauloel7** [comment]
So..... following the list above, here's some new additions:
- Avenger Defense Bondmates Fix
- Custom Soldier Evac Zone Fix
- Clean Camera Angles Fix
- New Weapon Range Tables WOTC (its vanilla-only portion)
- [WOTC] Less Overwatch Lock Ups!

Also, with the new mac patch being released (...) and the updating of X@WOTCCommunityHighlander for mac, how do we know which fix or fix-like mods are included/incorporated here or not? In other words, apart from one's vanilla liking, how do we know which mods that offer some sort of fix we can and cannot subscribe for the purpose of X2HL, so that we can have the game to run with the least amount of bugs/CTD?

**Comment by Iridar** [comment]
An updated and comprehensive list, put together by paradoxgamer

https://docs.google.com/document/d/1dpL5zdk-HBjUEkokWmXiBnOGNLrBqjmvi-cugChzLTo/edit

The list needs to be reformatted and reviewed, to clearly separate bugfixes that are integrated into Highlander from those that are not.

**Comment by TeslaRage** [comment]
Converted the list into excel
https://docs.google.com/spreadsheets/d/1Z5uUUzXZCvgoJQT8CeCsj9RIxRCxu4lLTYZ-BfXR7sI/edit?usp=sharing

I went through some of them and added some comments. If anyone needs access just request and I will let you.

**Comment by yoshimo** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2012323571 , id call it bug, but people might say it's part of the gameplay.

**Comment by Iridar** [comment]
Any information in this issue has not been relevant for years. Closing.
