### ISSUE TITLE
Make attacks against for non-units be properly guaranteed

### ISSUE THREAD

**Issue by RealityMachina** [X2CommunityCore/X2WOTCCommunityHighlander#346]
Long story short, per the comments this block of code should make any hit against a target that's a non-unit (like the Chosen Sarcophagus) guaranteed:
```   
 if (UnitState != none && TargetState == none)
    {
        // when targeting non-units, we have a 100% chance to hit. They can't dodge or otherwise
        // mess up our shots
        m_ShotBreakdown.HideShotBreakdown = true;
        AddModifier(100, class'XLocalizedData'.default.OffenseStat, m_ShotBreakdown, eHit_Success, bDebugLog);
    }
```

But that check is run *after* the game applies built in hit and crit mods, such as the debuffs to aim Chain Shot and Rapid Fire use. Hence, using an ability like rapid fire or chain shot against a static target may result in a miss.

While fixing the hit chance modifier would be simple enough (moving it inside the `else if (UnitState != none && TargetState != none)` block), the crit chance modifier is another story: people might be expecting for crits to work against stationary targets depending on the ability, whereas not many will be expecting an ability to miss a target the game treats as though it was not missable.

**Comment by Iridar** [comment]
> But that check is run after the game applies built in hit and crit mods, such as the debuffs to aim Chain Shot and Rapid Fire use. Hence, using an ability like rapid fire or chain shot against a static target may result in a miss.

I don't understand, why is that? Why is the order of applying modifiers relevant here?

**Comment by Iridar** [comment]
> While fixing the hit chance modifier would be simple enough (moving it inside the else if (UnitState != none && TargetState != none) block), the crit chance modifier is another story: people might be expecting for crits to work against stationary targets depending on the ability, whereas not many will be expecting an ability to miss a target the game treats as though it was not missable.

The only crit modifier being considered is the `BuiltInCritMod`, which is not used by any of the base game / DLC abilities. So the only abilities that could ever crit non-unit targets are mod-added. I think it's safe to exclude those from consideration.

**Comment by Tedster59** [comment]
So commenting here because of an additional discovery, this handles BuiltInHitMod, but does not handle abilities with a FinalMultiplier, such as Deadeye. If an ability has a less than 1.0 multiplier (e.g. an aim penalty), this will still get applied and can result in missing non-units.

![image](https://github.com/user-attachments/assets/daff37f2-a473-47c1-8ea7-0c46baf40110)

**Comment by Iridar** [comment]
```cpp
if (UnitState != none && TargetState == none)
{
	// when targeting non-units, we have a 100% chance to hit. They can't dodge or otherwise
	// mess up our shots
	m_ShotBreakdown.HideShotBreakdown = true;
	AddModifier(100, class'XLocalizedData'.default.OffenseStat, m_ShotBreakdown, eHit_Success, bDebugLog);
}
else if (UnitState != none && TargetState != none)
``` 
Honestly I feel a strong urge to just return 100 out of the first if() statement and call it a day. Since shots against non-units aren't supposed to have any other outcome than a hit, is there really a reason to process the rest of the modifiers and bother with hit chance finalization?

Same as with RollForHitChance, against interactive objects it should just short circuit return eHit_Success and be done with it.

**Comment by Tedster59** [comment]
that seems reasonable to me. That would also avoid a LW issue where graze band gets added to them as well, since the OverrideFinalHitChanceFn doesn't get any info about target or ability being used..

**Comment by Iridar** [comment]
That function is a massacre.
