### ISSUE TITLE
Pistol/sidearm animation bug - primary weapon used instead

### ISSUE THREAD

**Issue by korgano** [X2CommunityCore/X2WOTCCommunityHighlander#42]
This is a base WOTC bug I've noticed when using suppression on pistols/sidearms and occasionally when just firing the pistol - [the game will use the primary weapon](https://www.reddit.com/r/Xcom/comments/6zarvb/the_ol_enemy_unknown_sniper_pistol/), even though that's not the intended behavior.

**Comment by robojumper** [comment]
There's something really funny with Secondary weapons,

There's a consistent way to reprduce it: Whenever a unit attacking with a secondary weapon does an attack that is interrupted, some visualizer code switches to the primary weapon, resulting in sword users using their gun butt.

**Comment by Lady-Luck** [comment]
I think the mod Primary Secondaries found a workaround for this problem?

**Comment by Iridar** [comment]
I'm reproducing this issue by putting an Advent Stun Lancer and a Covering Fire overwatching Specialist on neighboring tiles. During the enemy turn, stun lancer tries to Stun Lance the specialist, but gets interrupted and damaged by Covering Fire and then butt stocks the Specialist instead with their rifle, still applying Stun Lance's damage and effects.

According to the visualization tree drawn by `X2DebugVisualizers`, the entire Covering Fire attack gets inserted between Stun Lance's `X2Action_ExitCover` and its `X2Action_Fire`. Perhaps, "putting distance" between these two actions is what's causing the problem?

Judging by some tests I did with logging, `X2Action_Fire` properly finds and uses the the visualizer of the weapon that is used for the ability. Calling `UnitPawn.SetCurrentWeapon()` in various places of `X2Action_Fire` didn't change anything either.

I believe the problem is with the game failing to find the correct AnimSet to draw the animsequence from to be played with `UnitPawn.GetAnimTreeController().PlayFullBodyDynamicAnim(AnimParams);` in the fire action. Unfortunately, I have no idea where that code is located. `PlayFullBodyDynamicAnim()` is native, so the investigation ends there.

**Comment by Iridar** [comment]
Another reliable way to produce this behavior is to have a Ranger Bladestorm and enemy grenade throw. The enemy will then fire the grenade with their primary rifle. This happens without any mods running too, so it's not induced by CHL or something, it's a genuine visualization bug by Firaxis.

**Comment by Iridar** [comment]
The end of `X2Action_ExitCover::Executing` has the following snippet:

```cs
//If the ability which generated this exit cover was interrupted, then process that here
if( !bSkipExitCoverVisualization && HasNonEmptyInterruption() )
{		
	//We don't want anyone messing up our step out / fire sequence. ( ie. flinches, get hit anims, etc. ). But we only care if there is a resume. If there is no
	//resume it means we died or otherwise cannot finish this action.
	if(VisualizationBlockContext.GetResumeState() != none)
	{
		UnitPawn.GetAnimTreeController().SetAllowNewAnimations(false); 
	}		
	else
	{
		if (Unit.TargetingCamera != None)
			`CAMERASTACK.RemoveCamera(Unit.TargetingCamera);
	}
	bAllowInterrupt = true;
	CompleteActionWithoutExitingExecution();
}
else
{
	CompleteAction();
}
```

You can see the intended logic in dev comments, but it doesn't seem to actually work. `VisualizationBlockContext.GetResumeState()` returns `none`, and `SetAllowNewAnimations()` doesn't run. 

However, even when I bypass the check and call `SetAllowNewAnimations()` anyway, the enemy unit just T-poses while it's being hit by Bladestorm, and then flings the grenade with the rifle anyway.

**Comment by Iridar** [comment]
I figured the native `XComGameStateContext::GetResumeState()` might be broken, so I reimplemented it in Unreal Script, which seemingly functioned as intended. 

However, the visualization remained broken and the `VisualizationBlockContext.GetResumeState()` in `X2Action_ExitCover` still returned `none`.

I went to look what is `VisualizationBlockContext`, and it's in `X2Action`:
```
//Deprecated
var protected XComGameStateContext_Ability VisualizationBlockContext;  //Points to the context that this action is a part of when Init is called ( ie. when this action starts running ).
```
Well that's just dandy.

**Comment by Iridar** [comment]
Contrary to the "deprecated" comment, there is code that interacts with `VisualizationBlockContext` in the way that looks like it should be working.

However, `VisualizationBlockContext.ResumeHistoryIndex` is `-1`, even though there *is* a version of context where it is set properly.

---

So I get two contexts, let's say Context 71 with Resume Index and Context 74 with Interruption Index.

I'm not sure why the Resume Context comes later than Interruption Context.

However, the important part is that `VisualizationBlockContext` is the Context 74, the Interruption Context, not the Resume Context.

**Comment by Iridar** [comment]
Notably, in vanilla XCOM 2 the interruption visualization works just fine at least as far as grenade throw and bladestorm are concerned. So it appears it was broken by WOTC.

**Comment by Iridar** [comment]
In vanilla it looks like this: enemy performs exit cover animation, triggers the Bladestorm attack, gets frozen, gets hit by the attack, without flinching or otherwise reacting to it. When Bladestorm visualization finishes, enemy continues with the throwing animation. 

In WOTC, enemy begins performing exit cover animation, which is interrupted when the Bladestorm attack animation starts. Until the enemy is hit by Bladestorm, they perform their idle breathing animation. When they are hit by Bladestorm, they perform the hurt/flinching animation. Once it finishes, they proceed with the grenade throw animation, which visualizes as the rifle attack. 

It appears that in WOTC whatever is supposed to freeze the enemy unit while they are being hit fails to work. You would think it's the `SetAllowNewAnimations()`, but that one just makes the enemy T-pose during the Bladestorm attack instead of playing the flinch animation, but their throw still visualizes as a rifle shot.

**Comment by Iridar** [comment]
I'm comparing vanilla X2Action_ExitCover to WOTC's:

# Vanilla

```cs
//If the ability which generated this exit cover was interrupted, then process that here
if( !bSkipExitCoverVisualization && VisualizationBlockContext.InterruptionStatus == eInterruptionStatus_Interrupt )
{		
	//We don't want anyone messing up our step out / fire sequence. ( ie. flinches, get hit anims, etc. ). But we only care if there is a resume. If there is no
	//resume it means we died or otherwise cannot finish this action.
	if(VisualizationBlockContext.GetResumeState() != none)
	{
		UnitPawn.GetAnimTreeController().SetAllowNewAnimations(false); 
	}		
	else
	{
		if (Unit.TargetingCamera != None)
			`CAMERASTACK.RemoveCamera(Unit.TargetingCamera);
	}
	bAllowInterrupt = true;
}
else
{
	CompleteAction();
}
```

# WOTC

```cs
//If the ability which generated this exit cover was interrupted, then process that here
if( !bSkipExitCoverVisualization && HasNonEmptyInterruption() )
{		
	//We don't want anyone messing up our step out / fire sequence. ( ie. flinches, get hit anims, etc. ). But we only care if there is a resume. If there is no
	//resume it means we died or otherwise cannot finish this action.
	if(VisualizationBlockContext.GetResumeState() != none)
	{
		UnitPawn.GetAnimTreeController().SetAllowNewAnimations(false); 
	}		
	else
	{
		if (Unit.TargetingCamera != None)
			`CAMERASTACK.RemoveCamera(Unit.TargetingCamera);
	}
	bAllowInterrupt = true;
	CompleteActionWithoutExitingExecution();
}
else
{
	CompleteAction();
}

```

I don't actually know what is returned by `VisualizationBlockContext.GetResumeState()` in vanilla, it does fail to get the game state in WOTC, presumably due to using the wrong `VisualizationBlockContext`.

**Comment by Iridar** [comment]
I found the cause of the problem. The blame is with two different places in code calling `XGUnitNativeBase::ResetWeaponsToDefaultSockets()`. 

## Problem 1

The first one is `XGUnitNativeBase::TimedGoToIdle()`, called by neighboring `XGUnitNativeBase::OnActionCompleted()`, which presumably runs whenever the XGUnit finishes playing an X2Action.

It checks if the unit has no X2Action currently playing, or if the X2Action is completed, and sets a 0.2 second timer to call the `TimedGoToIdle()`, which in turn does the same checks, and if they succeed, the `ResetWeaponsToDefaultSockets()` is called.

Presumably, the general idea is that after completing each X2Action, if another X2Action isn't queued for the unit very shortly, the unit is considered idle, and has their weapons reset and idle state machine resumed.

What it doesn't account for is that interrupted X2Actions still count as complete, otherwise the visualization wouldn't be able to proceed. 

So what happens is X2Action_ExitCover gets interrupted, and while the interrupting unit is visualizing their interrupting attack, the interrupted unit is assumed idle, and gets their weapons reset, which breaks the visualization of their interrupted attack once its resumed.

### Solution 1

Since both `OnActionCompleted()` and `TimedGoToIdle()` do the following check:
```cs
if (CurrentAction == None || CurrentAction.bCompleted)
```
Adjusting it to:
```cs
if (CurrentAction == None || CurrentAction.bCompleted && !CurrentAction.bInterrupted)
```

Effectively solves the problem.

## Problem 2

`X2Action_ApplyWeaponDamageToUnit::Executing()`  also calls `ResetWeaponsToDefaultSockets()` if the `ShouldPlayAnimation()` check succeeds.

`ShouldPlayAnimation()` checks if the X2Action wants to play an animation, and the unit is allowed to play animations.

The `X2Action_ExitCover` does forbid the unit to play animations when it is interrupted, as can be seen in code above.

It seems something allows the unit to play animations between `X2Action_ExitCover` and `X2Action_ApplyWeaponDamageToUnit`, so far I haven't been successful in finding that out.

So if the interrupting attack causes the interrupted unit to play hurt or flinch animation, it will also break the visualization of the interrupted attack.

Amusingly enough, making `ShouldPlayAnimation()` always return `false` does successfully resolve the bug, because `ResetWeaponsToDefaultSockets()` does not get called, but it does not prevent the interrupted unit from playing animations, they just always play the flinch animation, aka "the attack missed or hit someone else near me" animation.

Though I suspect it's actually being played by `X2Action_ApplyDamageToTerrain`, which makes all units near an attacked unit/tile to play flinch animations.

### Solution 2

I don't have a good solution to this one just yet. I have confirmed that the visualization does work with Solution 1 implemented and calls for `ResetWeaponsToDefaultSockets()` in `X2Action_ApplyWeaponDamageToUnit::Executing()` commented out. 

Here's how it looks: the interrupted enemy plays their exit cover animation, gets interrupted, plays flinch or hurt animation, then continues with their proper attack animation for grenade or stun lance.

Note that in vanilla (as intended by Firaxis), the interrupted unit does not play any animations caused by the interrupting attack.

Again, this does not happen in WOTC because something allows the interrupted unit to play animations after they have been forbidden by Exit Cover action.

However, I'm not sure this is a big problem, it looks pretty normal this way. 

But just commenting out calls for `ResetWeaponsToDefaultSockets()` isn't a proper solution, as there's likely a good reason Firaxis put it there. 

So it seems we have two reasonable solutions:

1. Find out what causes the interrupted unit to allow playing animations after they have been forbidden by interrupted `X2Action_ExitCover`, and fix it. That should make the interrupted unit completely freeze in place as they receive the interrupting attack, as intended by Firaxis.
2. Add a safeguard into `X2Action_ApplyWeaponDamageToUnit` that will prevent it from calling `ResetWeaponsToDefaultSockets()` if the damage action is being played as the result of an interrupting attack, which should be easy to do by recursively searching up the visualization tree for instances of `X2Action_MarkerInterruptBegin` playing on the same unit, which is a method used by `X2Action_ExitCover` itself to see if it's being interrupted.
