### ISSUE TITLE
Wrong ranks in rank up messages

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#526]
![grafik](https://user-images.githubusercontent.com/14299449/58134360-decba400-7c26-11e9-8679-cc60b7990ebe.png)

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/455560e52c6aa6e71c1e1cf0006efc42083c8d61/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_Unit.uc#L14068-L14078

Should not unconditionally use `GetRank()` internally.

Introduced by #416, cc @pledbrook, cc #408.

**Comment by robojumper** [comment]
(This also applies to the other two added functions below.)

**Comment by pledbrook** [comment]
What should it be conditionally checking for? All the code that got replaced used `GetRank()` unconditionally.

**Comment by pledbrook** [comment]
Oh wait, should it be `.static.GetRankName(Rank == -1 ? GetRank() : Rank, ...`? That looks like the mistake to me, but not sure.

**Comment by RealityMachina** [comment]
The issue is that `GetRank()` gets the unit's _current rank_, which does not change in tactical: the game marks them for promotion when a soldier does well enough in a mission, but otherwise what the game wants for the promotion message is the next rank above the current unit for that promotion message.

**Comment by robojumper** [comment]
Fixed in v1.18.2, which is live on GitHub and the Workshop.
