### ISSUE TITLE
Rocket launchers can fire through blocking tiles

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#617]
The `X2TargetingMethod_RocketLauncher` class has a bug where if the shooter of the rocket can step out, they can shoot the rocket through walls and other obstructions. This is because the code performs a ray trace between the unit's tile and its step out tile. The target tile isn't involved!

**Comment by MrNiceUK** [comment]
Well, to get the stepout option in the first place, does require LOS to the relevant tile, so it isn't a complete free-for-all as long as you're behind cover. Plus this bug has long obscured that the start point for the ray trace is a bit low. Hence the (not entirely wrong) believe by many players that SPARK rocket targeting is broken, since they can never take advantage of this bug, and should have an even higher starting point, but don't. Anyway, plenty more chatter about this on the Discord Channel!

**Comment by MrNiceUK** [comment]
Although, as covered in more detail on the issue/discord, the requirement of LOS to get stepout does *somewhat* mitigate the fallout from the bug.
