### ISSUE TITLE
"Control reached the end of non-void function" in mod dependency code

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#660]
Introduced in #525.

At least four functions have a missing return value in the standard code path
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/ab1485ddfc691d781d8cd04164d1e91807a0a96d/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2DownloadableContentInfo.uc#L637-L679

**Comment by robojumper** [comment]
cc @Musashi1584

**Comment by MrNiceUK** [comment]
Isn't the `(ModDependency != none && ModDependency.IgnoreRequiredMods.Length > 0)` check not require anyway? Can't see how the New operator can fail (even if DLCIdentifier is blank/none, that's the same as not passing the optional parameter in the first place?), and returning an empty array is the expected behaviour if the array is length zero?
