### ISSUE TITLE
Add Greater Control for Gremlin "Ghosts" in Staffslots - Attempt 3

### ISSUE THREAD

**Issue by VampireMonkey** [X2CommunityCore/X2WOTCCommunityHighlander#706]
Gimme a bit to get this right

**Comment by Iridar** [comment]
It seems only one mod had a potential use case for whatever this issue was supposed to address.  Previous attempts at this Issue (see #424 and #428) seem to be dead, and it's been over a year since this Issue has been filed, so I assume its implementation is not coming. Closing. 

Note for the future: no need to create a new Issue for each new PR. Generally there is no need to create an entirely new Pull Request if the previous implementation did not work either, it's always possible to rebase and force push.
