### ISSUE TITLE
Better cooked package replacement check

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#765]
Currently the version check is done via templates, which was invented when `XComGame` was the only package being replaced. This has 2 downsides:

1) Cannot use this info in `CreateTemplates` (or `OnPreCreateTemplates`)
2) It relies on `XComGame` creating templates for other packages, which makes it unreliable for error detection since it will report `Engine` replacement as missing if `XComGame` one wasn't loaded

While we cannot remove the existing approach due to BC, I propose we switch to a method of class-is-not-none and then getting default values, similar to how the `CHEngineVersion` template is created, in places which we control (eg. shell) and in future additions (eg. DLC2, #764)

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/fb9537d865af958d51cd94b0eaeee6e54df4b0a4/X2WOTCCommunityHighlander/Src/Engine/Classes/CHEngineVersion.uc#L1-L2

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/fb9537d865af958d51cd94b0eaeee6e54df4b0a4/X2WOTCCommunityHighlander/Src/XComGame/Classes/CHXComGameVersion.uc#L25-L35

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/fb9537d865af958d51cd94b0eaeee6e54df4b0a4/X2WOTCCommunityHighlander/Src/X2WOTCCommunityHighlander/Classes/X2WOTCCH_Components.uc#L46-L47

**Comment by robojumper** [comment]
There are two options, each with their own drawbacks:

1) We create entirely separate subclasses of `Object` in every package. We thus lose the reflective capabilities of the system, so we have to compile against every package whose version we want to check, as opposed to only `XComGame` with `CHXComGameVersionTemplate`

2) We create a common base class `CHAbstractVersion` with the relevant properties, and create a subclass in every package with `defaultproperties` so that users could load the CDO by name (either DLO or through `XCom?Engine`) and inspect it as a `CHAbstractVersion`. This makes the situation worse if the `Core` replacement fails to load because then all other subclass packages fail to load entirely.

**Comment by Xymanek** [comment]
> We thus lose the reflective capabilities of the system

Could you elaborate on this?

**Comment by robojumper** [comment]
We can't check the version of a component by name anymore, we have to use the specific class and we have to have compiler against this class beforehand. Compared to the current system, where we only need the template type and can request and inspect them by name without requiring building against `CHCoreVersion`, for example.

**Comment by Xymanek** [comment]
I see no issue in needing to build against all CHL-replaced packages if you want to check all of their versions. Why would you do otherwise?

> Compared to the current system, where we only need the template type 

Which sits in `XComGame` and will poof if said replacement isn't loaded

**Comment by robojumper** [comment]
Let's go with your approach. The improvements far outweigh the drawback I mentioned.

**Comment by Xymanek** [comment]
Fully implemented in #764
