### ISSUE TITLE
Add UnitDying Event to OnUnitDied in XComGameState_Unit

### ISSUE THREAD

**Issue by VampireMonkey** [X2CommunityCore/X2WOTCCommunityHighlander#766]
UnitDying will fire before UnitDied allowing mods to interrupt the whole process.

Some form of data has to be sent back and forth from the event to the function to interrupt it.

It could be a tuple with a boolean

The event will fire at the top of the function before everything else

**Comment by Iridar** [comment]
There is already an event preceding `'UnitDied'`, it is `'UnitTakeEffectDamage'`. It triggers after the damage was added to the `DamageResults` array, as well as after `'LastEffectDamage'` unit value has been set. A mod can listen to the `'UnitTakeEffectDamage'` and then simply increase unit's current HP by the amount necessary for the unit to survive this damage effect.

While this may not be as elegant as simply passing "don't kill this unit" bool flag to an event listener, it is a perfectly workable solution, so I don't think this Issue is necessary. Closing because of this and lack of interest for nearly a year.
