### ISSUE TITLE
Add an event to XCGS_Unit::ApplyInventoryLoadout

### ISSUE THREAD

**Issue by jeb3** [X2CommunityCore/X2WOTCCommunityHighlander#800]
Add an 'OnInventoryLoadoutApplied' event to XCGS_Unit::ApplyInventoryLoadout so that mods can change Unit's loadout after it has been applied. I want to use this for a mod that changes a rookie's starting primary weapon depending on their nationality. Could be used by any other mods that want to dynamically change a soldier's starting loadout.

**Comment by Iridar** [comment]
Closing this issue, because the proposed implementation does not work for the specified use case. See #948 ([comment link](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/948#issuecomment-759106176)) for details.

If anybody has some other use case for these events, feel free to comment in #948.
