### ISSUE TITLE
Warn if framerate smoothing is enabled

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#817]
Similar to the mod compatibility feature, I think the CHL should warn about framerate smoothing being enabled, since that is known to break a lot of stuff, namely MCOs.

A less "annoying" approach would be to check first if there is anything to be broken by it (e.g. an MCO)

**Comment by robojumper** [comment]
> A less "annoying" approach would be to check first if there is anything to be broken by it (e.g. an MCO)

There's not enough information about that particular interaction. If it has false positives, it shouldn't be a default warning. If it occurs, does it break all MCOs+ScreenListeners at once? Does toggling that option help more than simply restarting the game?

If both of these are true, my suggestion would be: Add `SomeClass` and `SomeSubClass extends SomeClass` to the `X2WOTCCommunityHighlander` package, add a MCO for `SomeSubClass` to override `SomeClass`, then check if `new`ing `SomeClass` yields an object of class `SomeSubClass`. If not, the override is broken.

**Comment by Dragon-32** [comment]
I've heard a number of times that this is a problem, but never actually experienced any effect from having it enabled.

**Comment by Iridar** [comment]
I ran some tests. 

[Test suite repo](https://github.com/Iridar/MCOTEST)

[CHL branch](https://github.com/Iridar/X2WOTCCommunityHighlander/tree/framerate-smoothing-tests)

In short, I adjusted the `XCGS_Unit::NumAllActionPoints()` in Highlander to this:

```
function int NumAllActionPoints()
{
	return 1337;
}
```

Then I set up a mod project that MCOs `XCGS_Unit` and overrides the function with this:

```
function int NumAllActionPoints()
{
	return 451;
}
```

And into X2DLCInfo class of the mod project I put this code:

```
static event OnPostTemplatesCreated()
{
	local XComGameState_Unit UnitState;

	UnitState = new class'XComGameState_Unit';

	`LOG(UnitState.Class.Name @ UnitState.NumAllActionPoints(),, 'IRITEST');
}
```

# Tests performed

Baseline: Framerate Smoothing disabled.
`[0024.80] IRITEST: XComGameState_Unit_Override 451`

Framerate Smoothing enabled.
`[0014.84] IRITEST: XComGameState_Unit 1337`

Framerate Smoothing disabled again.
`[0014.67] IRITEST: XComGameState_Unit 1337`

After deleting `%UserConfig%\XComEngine.ini`.
`[0008.86] IRITEST: XComGameState_Unit_Override 451`

# Takeaway

1. Framerate Smoothing does in fact break Mod Class Overrides.
2. After Framerate Smoothing is disabled, deleting `XComEngine.ini` is required to get them working again.

**Comment by Iridar** [comment]
I also ran some tests with a UISL, because I have a vague recollection that people say Framerate Smoothing breaks those too, but I couldn't confirm it. I used a simple UISL for `UIShell` to replace the text on all buttons to "Hijacked", and it worked regardless of the Framerate Smoothing status.

```
class UISL_1 extends UIScreenListener;

event OnInit(UIScreen Screen)
{
	local UIShell Shell;
	local UIX2MenuButton MenuButton;
	local array<UIPanel> Panels;
	local UIPanel Panel;

	Shell = UIShell(Screen);
	if (Shell == none)
		return;

	Shell.GetChildrenOfType(class'UIX2MenuButton', Panels);
	foreach Panels(Panel)
	{
		MenuButton = UIX2MenuButton(Panel);
		MenuButton.SetText("HIJACKED");
	}
}
```

**Comment by Iridar** [comment]
Here's the relevant code regarding the Framerate Smoothing option, all located in `UIOptionsPCScreen`:

```
function SetVideoTabSelected()
{
	local GFxObject VideoTabMC;
	ResetMechaListItems();

	// Other options created here

	// Frame Rate Smoothing toggle: --------------------------------
	m_arrMechaItems[ePCTabVideo_FRSmoothing].UpdateDataCheckbox(m_strVideoLabel_FRSmoothingToggle, "", GetCurrentFRSmoothingToggle(), UpdateFRSmoothing);
	m_arrMechaItems[ePCTabVideo_FRSmoothing].BG.SetTooltipText(m_strVideoLabel_FRSmoothingToggle_Desc, , , 10, , , , 0.0f);
	
}

simulated native function bool GetCurrentFRSmoothingToggle();

native function UpdateFRSmoothingNative(bool bUseFRSmoothing);

public function UpdateFRSmoothing(UICheckbox CheckboxControl)
{
	UpdateFRSmoothingNative(CheckboxControl.bChecked);
	m_GEngineValueChanged = true;
	m_bAnyValueChanged = true;

	Movie.Pres.PlayUISound(eSUISound_MenuSelect);
}
```

Some areas of the code read `m_kInitVideoSettings.bFRSmoothing`, where `m_kInitVideoSettings` is ``var TUIOptionsInitVideoSettings m_kInitVideoSettings; `, presumably initialized by native code.

**Comment by Iridar** [comment]
I made a console command that runs the same code as OPTC earlier, and tested what happens if I run the console command after enabling Framerate Smoothing without restarting the game. 

In this case enabling Framerate Smoothing had no effect, the MCO still worked, so the issue seems to come from having Framerate Smoothing enabled on game start.

I found this value in the freshly generated `XComEngine.ini`

```
[XComGame.XComEngine]
bSmoothFrameRate=False
```

**Comment by Iridar** [comment]
>  the issue seems to come from having Framerate Smoothing enabled on game start

So I see two ways this can be addressed. 

# 1. Kill Framerate Smoothing for good

Do not allow the player to even enable it, to prevent the situation where the player enables Framerate Smoothing and *then* adds some mods with MCOs.

**Arguments in favor:** enabling this option has no clear benefits, it solves the problem for good, and prevents people from ever stepping on this rake.

**Arguments against:** we would be forcing the solution on people, so the moral question is do you deny someone from having a rake just because they are likely to step on it?

## Implementation

To accomplish this, we would add this bit to Highlander's XComEngine.ini:

```
[XComGame.XComEngine]
bSmoothFrameRate=False
```

This will make sure Framerate Smoothing is disabled on game start, regardless of what the player sets in settings.

We could also hide or block the Framerate Smoothing option in the game settings, potentially offering a tooltip explanation as to why this option is disabled.

Personally I'm massively in favor of this option, and I'd be glad to implement it, given the go-ahead.

# 2. Display Warnings

Various warnings can be displayed:

1. Display a warning on game start if Framerate Smoothing is enabled and the player has active mods that have MCOs, which should be easy to check via `class'Engine'.default.ModClassOverrides.Length > 0`.
2. Display a warning if the player attempts to enabled Framerate Smoothing if they have active mods with MCOs.

**Arguments in favor:** allows people to "enjoy" Framerate Smoothing as long as they don't use mods with MCOs.
**Arguments against:** there will be people who will not understand or even read the warnings.

Even though I already expect robojumper and Xymanek to vote in favor of this solution, I personally feel it would be a waste of my time, so I'm not interested in implementing it myself.

**Comment by Iridar** [comment]
It might be worth testing to see if `class'XComEngine'.default.bSmoothFrameRate = false;` done in `OnPreCreateTemplates()` or somewhere feasibly earlier would fix the problem. In that case Framerate Smoothing can be forcibly disabled by Highlander if `class'Engine'.default.ModClassOverrides.Length > 0`. Highlander can then inform the player about this fact.

**Comment by Iridar** [comment]
```
if (class'Engine'.default.ModClassOverrides.Length > 0)
{
	class'XComEngine'.default.bSmoothFrameRate = false;
	class'Engine'.default.bSmoothFrameRate = false;
	//class'EditorEngine'.default.bSmoothFrameRate = false;
}
```
Tested by running this just before `OnPreCreateTemplates()`, didn't work. It seems the only way to properly disable it is via config.

**Comment by Iridar** [comment]
Tested some more, I can't figure out any way to reliably fix MCOs broken by Framerate Smoothing. It requires a config wipe. 

So the only things we can do are:

1. Prevent the user from ever enabling FS by shipping the config I posted above and making some UI changes to inform the user why FS can't be turned on. However, that will not fix MCOs broken by FS if the user *ever* had it enabled. It will also prevent us from knowing if the FS was currently enabled when they added the Highlander.
2. If FS is currently enabled, display a warning, informing the user that they need to regenerate config. However, this will not fire if the user enabled FS, then disabled FS, then added the Highlander. FS will show as disabled in that case.

I also expect 90% of people who see the warning to fail at understanding it. So I think the best method is prevention. We can also display some instructions in the tooltip for now-disabled FS if we go with the first option, so I think it's the best compromise.

**Comment by RustyDios** [comment]
If the button is disabled how can people turn it off? Do we enforce it by code?
Would disabling the button actually break the backwards compatibility policy?
I'm all for changing the tooltip though and adding a warning against the button's activation. I would also say making it a two-step dialogue(reason) with ok/cancel process would be good too. Click button > pop-up > confirm.

**Comment by Iridar** [comment]
> Do we enforce it by code?

Via config I posted earlier. 

> Would disabling the button actually break the backwards compatibility policy?

Well, this would technically be removing a feature, but BC policy applies to Highlander features, not game features, and only insofar that there might exist mods that rely on certain CHL behavior, so the point of the policy is to add new features in a way that existing mods continue to function as if nothing happened.

I don't think it applies to FS, because it's (A) not a CHL feature and (B) there aren't any mods that rely on it or could rely on it and (C) because it's responsible for breaking mods for countless people, most of whom I do not believe could follow the instructions to regenerate config to undo the damage done by FS. And (D) it makes no perceptible difference anyway. The world would be a better place if it just didn't exist, and Highlander is the best platform to get rid of it.

I suppose a config flag can be added to unlock FS for that one person who really cares about it more than having other mods working.

**Comment by Iridar** [comment]
Correction: BC policy does apply to game features, since they are technically indistinguishable from Highlander, as it replaces game's source code. So this would be a purposeful BC break, but so is every CHL bugfix, if you squint hard enough. Obviously FS is more of a grey area, but other arguments still apply.

**Comment by RustyDios** [comment]
Okay, as long as we are aware that we are intentionally making a BC-break here to fix a "common and widespread" bug with most/all MCO/UI mods. I would like to see this change, as I'm so tired of asking/telling people about this issue during bugfixing.
