### ISSUE TITLE
Allow other classes to be treated as Resistance Heroes for AP Generation / Perk allocation

### ISSUE THREAD

**Issue by kyuubicle** [X2CommunityCore/X2WOTCCommunityHighlander#87]
Currently, a native function IsResistanceHero() is called in functions such as HasAvailablePerksToAssign() or RankUpSoldier() that prevents any other classes from being able to fully use the same completely AP-based perk buying methods.

In particular, standard classes never get increasing amount of AP based on rank, it will always be whatever BaseAbilityPointsPerPromotion modified by combat intelligence is. Yet, the *costs* of perks for such classes *will* rise, causing such soldiers to be unable to assign a perk and finalize their ranking up without using XCom AP. 

Such soldiers also cannot gain further ranks without first assigning a perk of their current rank. Resistance Heroes actually check to see if they have enough AP rather than checking if they have a perk of their current rank; preventing this issue for them.

**Comment by robojumper** [comment]
One should probably add a function to XComGameState_Unit, something like `function bool UsesResistanceHeroRankup() { ... }` and use that one instead of `IsResistanceHero()` for all purposes of rank ups.

That's quite a lot of changes in `UIArmory_PromotionHero`, `UIPersonnel_TrainingCenter`, `UISoldierHeader`, `XComGameState_Unit`, `XComHQPresentationLayer`, and potentially some mods.

However, it should not break anything in the base game, and in the worst case, result in some mods not handling some custom classes correctly.

**Comment by Iridar** [comment]
I don't mind doing the legwork on this, but I could use some pointers first. What should the proposed `UsesResistanceHeroRankup()` method actually do? Trigger a CHL event for a potential override, and if there are no overriding mods, return the output of the native function? Something along those lines?..

**Comment by Iridar** [comment]
[Community Promotion Screen](https://github.com/X2CommunityCore/X2CommunityPromotionScreen) presently allows fully simulating the resistance hero promotion scheme.  

> increasing amount of AP based on rank

Can be easily added by a mod using the `'UnitRankUp'` event. 

So I'll be archiving this issue until there's an actual use case for it.
