### ISSUE TITLE
Streamline NumUpgradeSlots for X2ItemTemplates

### ISSUE THREAD

**Issue by Musashi1584** [X2CommunityCore/X2WOTCCommunityHighlander#93]
To extend upgrade slots to items other then weapons and make them accessible to modders
add `GetNumWeaponUpgradeSlots()` to `X2ItemTemplate`
and use it in all places that currently access `X2WeaponTemplate(Template).NumUpgradeSlots`.

`GetNumWeaponUpgradeSlots` returns  `NumUpgradeSlots` if set (in case of `X2WeaponTemplate`) or reads the value from a helper config array.

Also add a function `GetNumWeaponUpgradeSlots` in `XComGameState_Item` that considers breakthroughs, and adds a way for mods to modify the output.

Pitfalls: Lookout for code that relies on weapons be the only items that use attachements.

**Comment by GingerAvalanche** [comment]
Most errors that come up as a result of attaching a weapon upgrade to something that doesn’t have an X2WeaponTemplate are cosmetic in nature - UI pictures not appearing because the picture is based on the item you’re equipping to, for example - and most, if not all, are in UIArmory_WeaponUpgrade, UIArmory_WeaponUpgradeItem, UIArmory_LoadoutItem, and UIArmory_LoadoutItemTooltip. May want to leave this up to modders to assign their own pictures and icons, but some catch-all conditions should be added to avoid bad formatting in item descriptions.

UIArmory_WeaponUpgrade also contains the Armory function that checks how many upgrade slots to let the player fill. Grimy’s Loot Mod currently overrides this, but placing an event there that can be hooked into would improve compatibility between it and other future mods that may add different ways of handling NumUpgradeSlots. (e.g. Loot Mod, which stores and handles individual NumUpgradeSlots on a per-GameState basis)

**Comment by GingerAvalanche** [comment]
Finally getting around to this, almost a year later. What a ride.

Will be adding `GetNumUpgradeSlots()` to `X2ItemTemplate` which will return NumUpgradeSlots if `self` is castable to `X2WeaponTemplate`. Otherwise, it will search an array of UpgradeSlotHelper structs and, if found, return the number of upgrade slots from that struct.

`GetNumUpgradeSlots()` in `XComGameState_Item` will fire an event that will allow mods to override the number on a per-gamestate basis. If a mod sets an XComLWTuple to true, the game will use whatever value is in a second tuple, otherwise it will call `X2ItemTemplate::GetNumUpgradeSlots()`.

Everything that checks weapon templates for upgrade slots already checks for breakthroughs immediately thereafter, so the breakthrough check can be skipped.

**Comment by robojumper** [comment]
FWIW, I'm not a huge fan of passing "override booleans" -- just pass a single integer as the first tuple element that contains the result of `X2ItemTemplate:GetNumUpgradeSlots`. That way, mods can do things like modifying the existing value etc.

**Comment by Musashi1584** [comment]
@GingerAvalanche any chance you gonna submit a PR for this? If not I might give this a go sometime.

**Comment by GingerAvalanche** [comment]
Yeah, I got distracted by yet another thing. The entire branch of changes I was looking to do isn’t done yet (and may never be if I keep getting distracted for years) but this issue can finally be done with.
